### ISSUE TITLE
The released zip files don't include the files in the cmake directory.

### ISSUE THREAD

**Issue by charleseidsness** [zeek/bifcl#2]

**Comment by jsiwek** [comment]
The zip files associated with tagged releases are automatically generated by GitHub with no way to disable them or to instruct it to recursively include files within git submodules, so we can't fix it.

I'm curious if you made this issue inside this `bifcl` repo on purpose or are you actually interested in `zeek` (aka `bro`) ?  To workaround GitHubs `.zip` file issue for the later, we do upload a custom `.tar.gz` file which does include submodule files.  We could do the same for `bifcl`, just didn't really expect people to be using it directly for anything (except potentially to support cross-compiling use-cases).

**Comment by charleseidsness** [comment]
Thanks.

We're using it because we are cross compiling, we can just do a git clone instead on using the released packages.
